# Generated by Django 4.2.4 on 2023-10-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_amount_item_user'),
        ('main', '0005_item_amount'),
    ]

    operations = [
    ]
